### ISSUE TITLE
Daemon: 使用统一的Logger(Serilog)

### ISSUE THREAD

**Issue by AresConnor** [MCSLTeam/MCServerLauncher-Future#8]
Daemon使用Serilog统一Logger，尤其避免使用ServerBehavior中的Log，并做相应的格式配置( 时间,等级,发出者,信息等..) 以及日志分级，还有输出到控制台/文件，以提供完整的程序运行状态,方便调试

**Comment by lxhtt** [comment]
那目前为止只需要做好格式化了

**Comment by AresConnor** [comment]
> 那目前为止只需要做好格式化了

ok，目前的打算是暂时给Remote包搞个LogHelper，打印[Remote]前缀，然后之后的包每个包一个helper，打印[xxx]前缀
